org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.org.gradle.internal.http.connectionTimeout=45000

mod.id=space_m
mod.name=Space Modernized
mod.group=com
mod.version=0.1.0
mod.channel_tag=-alpha
mod.authors=
mod.contributors=
mod.license=GPL-3.0-only
mod.description=
mod.sources_url=
mod.homepage_url=
mod.issues_url=
mod.discord_url=
mod.mixin_config=mixins.space_m.json
mod.mixin_refmap=mixins.space_m.refmap.json

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]
deps.architectury=[VERSIONED]
deps.hbm_m=[VERSIONED]

publish.modrinth=
publish.curseforge=
publish.github=false
