deps.minecraft=1.20.1
deps.forge=47.4.20
deps.javafml_range=[47,)
deps.forge_dependency_range=[47.3.31,)
deps.minecraft_dependency_range=[1.20.1]
deps.architectury=9.2.14
deps.hbm_m=0.2.2-alpha+1.20.1-forge
# deps.parchment=1.20.1:2023.09.03

publish.additionalVersions=
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot
